baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Bytethesis'
theme = "bytethesis"
summaryLength = 25

[Params]
    description = 'Bytethesis um site sobre programação e tecnologia. Aqui você encontrará uma variedade de conteúdos incluindo novidades e tutoriais, o objetivo desse blog é compartilhar conhecimento e aprender no caminho.'

[taxonomies]
    category = 'categories'
    tag = 'tags'
  
[outputs]
    home = [ "HTML", "JSON", "RSS"]

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files